### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by gokaygurcan** [SalesforceCommerceCloud/sfcc-ci#159]
Hi,

It'd be really nice if we have this package as a GitHub Action. So that we could do something like: 

```yml
name: Deploy Code
on: [ push ]

env:
    SFCC_OAUTH_CLIENT_ID: ${{ secrets.SFCC_OAUTH_CLIENT_ID }}
    SFCC_OAUTH_CLIENT_SECRET: ${{ secrets.SFCC_OAUTH_CLIENT_SECRET }}
    SFCC_OAUTH_USER_NAME: ${{ secrets.SFCC_OAUTH_USER_NAME }}
    SFCC_OAUTH_USER_PASSWORD: ${{ secrets.SFCC_OAUTH_USER_PASSWORD }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./output/code.zip ./cartridges
      - name: code:deploy
        uses: SalesforceCommerceCloud/sfcc-ci@latest
        id: deploy
        run: code:deploy ./output/code.zip -i ${{ secrets.INSTANCE_URL }}
```

I don't know, this might not be a good example and might not even work, but should be enough to understand the idea.
